
-- Table: representative_url
-- DROP TABLE representative_total_income;
CREATE TABLE representative_total_income
(
  id serial NOT NULL,
  representative_id integer,
  ad_id integer NOT NULL,
  ad_submission_date date NOT NULL,
  ad_entrepeunerial_income integer,
  ad_paid_work_income integer,
  CONSTRAINT representative_total_income_pkey PRIMARY KEY (id),
  CONSTRAINT representative_id_refs_person_ptr_id FOREIGN KEY (representative_id)
      REFERENCES representative_representative (person_ptr_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED
)
WITH (
  OIDS=FALSE
);
ALTER TABLE representative_total_income
  OWNER TO shenmartav;
-- Index: representative_url_representative_id
-- DROP INDEX representative_url_representative_id;
 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka=' თარგამაძე'),1),45676,2013-05-07,0,61539) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='აზერ სულეიმანოვი'),1),45799,2013-05-13,0,53776.03) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='აკაკი ბობოხიძე'),1),45894,2013-05-13,0,63202) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='აკაკი მინაშვილი'),1),46044,2013-05-25,0,66367.5) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ალექსანდრე თამაზაშვილი'),1),44534,2013-01-16,0,11500) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ალექსანდრე ტაბატაძე'),1),47815,2013-11-14,0,51856.7) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ალექსანდრე ქანთარია'),1),48051,2013-12-10,0,1000) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ალექსი პეტრიაშვილი'),1),44047,2012-12-12,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ალი მამედოვი'),1),44038,2012-12-19,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ანზორ ბოლქვაძე'),1),45697,2013-05-08,0,69717.91) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ანი მიროტაძე'),1),44041,2012-12-17,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='არჩილ კბილაშვილი'),1),44026,2012-12-21,80000,79674.85) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ბიძინა გუჯაბიძე'),1),44099,2012-12-21,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გედევან ფოფხაძე'),1),48091,2013-12-13,0,15074.2) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გელა გელაშვილი'),1),44007,2012-12-19,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გელა სამხარაული'),1),44053,2012-12-21,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გელა ხვედელიძე'),1),44089,2012-12-17,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გია ჟორჟოლიანი'),1),44050,2012-12-18,0,19200) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიგა ბუკია'),1),44005,2012-12-20,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიგლა აგულაშვილი'),1),48061,2013-12-13,0,14601.23) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი ბარამიძე'),1),45794,2013-05-18,2350,640500) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი გაბაშვილი'),1),46141,2013-05-27,0,70495) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი გაჩეჩილაძე'),1),44006,2012-12-19,0,30429) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი გოზალიშვილი'),1),46887,2013-08-27,0,36867.6) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი ვაშაძე'),1),46291,2013-06-07,0,65417.5) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი ვოლსკი'),1),44018,2012-12-21,0,34013.86) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი თევდორაძე'),1),46889,2013-08-27,0,44094) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი თოფაძე'),1),44022,2012-12-21,0,69204.75) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი კანდელაკი'),1),46249,2013-06-04,0,56706) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი კარბელაშვილი'),1),45162,2013-04-05,0,54923.38) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი კახიანი'),1),46706,2013-07-17,7125,34560) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი მელაძე'),1),45995,2013-05-21,0,67719.61) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი ოჩიაური'),1),44045,2012-12-14,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი ჟვანია'),1),44049,2012-12-21,96400,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი ფეიქრიშვილი'),1),46497,2013-07-01,0,51092.619999999995) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი ქავთარაძე'),1),44063,2012-12-20,0,5250) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი ღვინიაშვილი'),1),45888,2013-05-15,0,61474) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი ცაგარეიშვილი'),1),45973,2013-05-17,0,52223) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი წერეთელი'),1),45958,2013-05-23,0,76377) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი ხაჩიძე'),1),45956,2013-05-15,0,64722.22) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გიორგი ხეჩინაშვილი'),1),44088,2012-12-19,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გოგი ლიპარტელიანი'),1),45771,2013-05-14,0,63488.46) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გოდერძი ბუკია'),1),45976,2013-05-21,0,52135.42) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გოჩა ენუქიძე'),1),46001,2013-05-24,1.6314997400000002E6,52886.72) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გუბაზ სანიკიძე'),1),47891,2013-11-13,0,17716.26) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გუგული მაღრაძე'),1),44039,2012-12-18,0,23800) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='გურამ მისაბიშვილი'),1),45934,2013-05-16,0,59053) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='დავით ბაქრაძე'),1),45957,2013-05-24,0,92742) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='დავით ბეჟუაშვილი'),1),46053,2013-05-27,0,53668.45) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='დავით ბერძენიშვილი'),1),47587,2013-11-08,0,25883) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='დავით დარჩიაშვილი'),1),45798,2013-05-13,0,99412) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='დავით დარცმელიძე'),1),45977,2013-05-23,0,41087.05) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='დავით ონოფრიშვილი'),1),44044,2012-12-21,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='დავით საგანელიძე'),1),44052,2012-12-22,26000,28000) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='დავით საყვარელიძე'),1),45558,2013-05-04,0,35507) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='დავით უსუფაშვილი'),1),44060,2012-12-20,0,48468.25) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='დავით ჭავჭანიძე'),1),45705,2013-05-10,0,49000) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='დათო ლორთქიფანიძე'),1),44539,2012-12-28,0,12000) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='დემურ ბაშელეიშვილი'),1),48021,2013-12-06,0,15098) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='დიმიტრი ხუნდაძე'),1),44092,2012-12-19,0,55000) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ეთერ სვიანაიძე'),1),47737,2013-11-11,0,48273) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ეკა ბესელია'),1),44003,2012-12-19,0,24750) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ელისო ჩაფიძე'),1),44073,2012-12-18,0,15016) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ენზელ მკოიანი'),1),45935,2013-05-21,0,50952) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ერეკლე ტრიპოლსკი'),1),44058,2012-12-21,0,42000) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ვალერი გელაშვილი'),1),44008,2012-12-20,20712,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ვაჟა ჩიტაშვილი'),1),45390,2013-04-23,0,77335.81) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ვახტანგ ლემონჯავა'),1),46963,2013-09-11,0,49665.450000000004) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ვახტანგ ხმალაძე'),1),47806,2013-11-10,10710,55682.28999999999) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ვიქტორ დოლიძე'),1),48029,2013-12-10,0,17689.36) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ვიქტორ ჯაფარიძე'),1),48090,2013-12-17,0,84957.5) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ზაზა კედელაშვილი'),1),44027,2012-12-20,9600,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ზაზა პაპუაშვილი'),1),48052,2013-12-13,0,39431.32) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ზაქარია ქუცნაშვილი'),1),44066,2012-12-21,103800,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ზვიად კვაჭანტირაძე'),1),44030,2012-12-21,63180,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ზვიად ძიძიგური'),1),44077,2012-12-20,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ზურაბ აბაშიძე'),1),43996,2012-12-20,0,43300) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ზურაბ ზვიადაური'),1),44020,2012-12-21,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ზურაბ კიკალეიშვილი'),1),43992,2012-12-16,0,51086) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ზურაბ მარაქველიძე'),1),47886,2013-11-13,0,14497.28) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ზურაბ მელიქიშვილი'),1),46054,2013-05-24,0,68227.52) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ზურაბ ტარიელაშვილი'),1),47574,2013-11-07,0,48468) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ზურაბ ტყემალაძე'),1),44059,2012-12-21,0,45000) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ზურაბ ჩილინგარაშვილი'),1),48079,2013-12-12,0,29000) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ზურაბ ჯაფარიძე'),1),44094,2012-12-21,0,66206.85) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='თამაზ ავდალიანი'),1),43998,2012-12-20,0,10946.7) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='თამაზ კვაჭანტირაძე'),1),43991,2012-12-19,0,59132.49) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='თამაზ მეჭიაური'),1),44535,2013-01-09,0,10771.71) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='თამაზ ყაჭეიშვილი'),1),44069,2012-12-20,24000,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='თამაზ შიოშვილი'),1),48138,2013-12-18,0,10771.71) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='თამაზ ჯაფარიძე'),1),44096,2012-12-21,0,4440) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='თამარ კორძაია'),1),46704,2013-07-18,0,35000) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='თამარ ყოლბაია'),1),44694,2013-01-23,0,28000) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='თეა წულუკიანი'),1),44080,2012-12-21,0,5396.48) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='თედო ჯაფარიძე'),1),48171,2013-12-18,0,17966.55) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='თეიმურაზ ჩხაიძე'),1),48062,2013-12-13,0,14727.17) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='თეიმურაზ ჭკუასელი'),1),48164,2013-12-18,0,14727.17) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='თემურ მაისურაძე'),1),44036,2012-12-21,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='თენგიზ ხუბულური'),1),44531,2012-12-18,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='თინათინ ბოკუჩავა'),1),46340,2013-06-12,0,41577.17) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='თინათინ ხიდაშელი'),1),44090,2012-12-20,0,63883.8) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='იაშა შერვაშიძე'),1),45800,2013-05-10,0,53480.14) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ივანე კიღურაძე'),1),47883,2013-11-12,0,43372.259999999995) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='იოსებ ჯაჭვლიანი'),1),47987,2013-12-03,0,29658) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ირაკლი ალასანია'),1),43999,2012-12-21,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ირაკლი სესიაშვილი'),1),44056,2012-12-17,0,46703.67) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ირაკლი ჩიქოვანი'),1),44075,2012-12-19,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ირინე იმერლიშვილი'),1),44023,2012-12-21,0,27000) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ირმა ნადირაშვილი'),1),46829,2013-08-22,0,47699.59) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='კარლო კოპალიანი'),1),45882,2013-05-16,0,57052) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='კარლო ცქიტიშვილი'),1),8786,2012-11-09,0,43943.97) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='კახა ბუცხრიკიძე'),1),44553,2013-01-26,0,23000) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='კახა კალაძე'),1),44024,2012-12-22,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='კახაბერ ოქრიაშვილი'),1),46193,2013-05-30,1.177224E7,52152.68) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='კობა დავითაშვილი'),1),44012,2012-12-20,0,23095) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='კობა ნაყოფია'),1),46188,2013-05-31,0,53175.48) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='კობა სუბელიანი'),1),45776,2013-05-13,0,59306.32) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ლაშა ნაცვლიშვილი'),1),44042,2012-12-21,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ლევან ბეჟაშვილი'),1),45979,2013-05-25,0,48419.93) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ლევან ბერძენიშვილი'),1),47738,2013-11-08,0,23548) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ლევან ქარდავა'),1),44065,2012-12-21,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ლერი ხაბელოვი'),1),44083,2012-12-21,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='მაია ფანჯიკიძე'),1),44061,2012-12-17,0,9000.29) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='მაკა გიგაური'),1),46321,2013-05-14,0,53957) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='მალხაზ ვახტანგაშვილი'),1),44017,2012-12-19,0,4200) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='მალხაზ წერეთელი'),1),44078,2012-12-17,0,4250) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='მანანა კობახიძე'),1),44034,2012-12-21,0,29819.74) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='მარიამ საჯაია'),1),44055,2012-12-21,0,5400) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='მარიკა ვერულაშვილი'),1),46107,2013-05-27,0,53011.58) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='მარინე ასათიანი'),1),47628,2013-11-08,0,50005) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='მახირ დარზიევი'),1),44536,2012-12-24,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='მერაბ გოცირიძე'),1),47863,2013-11-15,0,50892) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='მერაბ კაჭახიძე'),1),44025,2012-12-20,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='მირიან წიკლაური'),1),44079,2012-12-21,0,18520) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='მიხეილ მაჭავარიანი'),1),45907,2013-05-17,0,71488.2) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='მიხეილ მახარაძე'),1),46202,2013-05-29,0,66199.37) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='მურთაზ შალუაშვილი'),1),47774,2013-11-08,0,43000) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='მურმან დუმბაძე'),1),47933,2013-11-21,0,29700) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ნანა ყეინიშვილი'),1),44070,2012-12-19,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ნაული ჯანაშია'),1),45801,2013-05-15,0,53776.03) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ნიკოლოზ ნერგაძე'),1),46697,2013-07-15,0,55537) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ნიკოლოზ ყიფშიძე'),1),44071,2012-12-21,0,377573) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ნინო გოგუაძე'),1),47941,2013-11-28,0,51781) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ნოდარ ებანოიძე'),1),44016,2012-12-21,0,18062) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ნოდარ ხადური'),1),44085,2012-11-09,0,52000) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ნუგზარ წიკლაური'),1),45793,2013-05-16,0,89455) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ოთარ ჩრდილელი'),1),44537,2013-01-12,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ომარ მეგრელიძე'),1),44040,2012-12-19,0,36000) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ომარ ნიშნიანიძე'),1),44540,2013-01-10,0,19383) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='პაატა ბარათაშვილი'),1),47760,2013-11-14,0,14829.12) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='პაატა ზაქარეიშვილი'),1),44019,2012-12-19,0,87962.24) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='პაატა კვიჟინაძე'),1),47946,2013-11-26,0,15316.26) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='პაატა კიკნაველიძე'),1),46705,2013-07-17,0,28688) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='პაატა ლეჟავა'),1),45893,2013-05-18,0,55401.25) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='პავლე კუბლაშვილი'),1),46151,2013-05-29,0,67799) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='პეტრე ცისკარიშვილი'),1),45974,2013-05-23,0,67617) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='რამაზ ნიკოლაიშვილი'),1),46035,2013-05-25,0,87987.17) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='რევაზ შავლოხაშვილი'),1),45638,2013-05-08,0,97890) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='როლანდ ახალაია'),1),45803,2013-05-12,0,60390) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='როსტომ ხალვაში'),1),44086,2012-12-19,0,9860) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='რუსლან პოღოსიანი'),1),48066,2013-12-13,0,14829) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='სამველ პეტროსიანი'),1),45300,2013-04-19,0,33841.03) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='სერგო რატიანი'),1),44051,2012-12-21,0,71134.8) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='სერგო ხაბულიანი'),1),47986,2013-11-28,2.538796E6,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='სოზარ სუბარი'),1),44057,2012-12-19,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ტარიელ ლონდარიძე'),1),48018,2013-12-09,0,45961) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ფატი ხალვაში'),1),44087,2012-12-15,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ფრიდონ საყვარელიძე'),1),48178,2013-12-18,0,14081) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='შალვა კიკნაველიძე'),1),44032,2012-12-13,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='შალვა შავგულიძე'),1),44072,2012-12-20,0,34906) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='შოთა გოშაძე'),1),47889,2013-11-14,0,28502.52) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='შოთა მალაშხია'),1),45704,2013-05-05,0,56745.58) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='შოთა ხაბარელი'),1),44082,2012-12-19,0,0) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='შორენა კახიძე'),1),47325,2013-10-21,0,47980.91) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ჩიორა თაქთაქიშვილი'),1),46248,2013-06-04,0,60124.61) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ხათუნა გოგორიშვილი'),1),46000,2013-05-22,0,79900.91) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ხათუნა უზნაძე'),1),47685,2013-11-06,0,48366) 
INSERT INTO representative_total_income (representative_id,ad_id,ad_submission_date,ad_entrepeunerial_income,ad_paid_work_income) 
 VALUES (COALESCE((SELECT person_id FROM popit_personname WHERE name_ka='ჰამლეტ სხულუხია'),1),47771,2013-11-13,0,51784)